server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: parola
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: mysql
      mode: always

cors:
  origin: http://localhost:4200

management:
  security:
    enabled: false
# ca sa ne conectam la keycloak
keycloak:
  realm: Tasks
  resource: Tasks-client-frontend #cum se numeste clientul
  public-client: true
  auth-server-url: http://localhost:8080/auth
  bearer-only: true
  ssl-required: external
  #use-resource-role-mappings: true
  #ssl-required: none


  #pentru ca sa ne conectam ca admin sa putem modifica chestii in keycloak (interfata de unde modificam noi manual)
admin-keycloak:
  username: admin
  password: admin
  realm: master
  client: admin-cli

